sudo: false
cache:
  - pip
  - npm
  - directories:
    - $HOME/.cache/pip
addons:
  firefox: "latest"
language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install less less-plugin-clean-css grunt-cli
  - export PATH=`pwd`/node_modules/.bin:$PATH
  - ./manage.sh install_geckodriver ~/drivers
  - export PATH=~/drivers:$PATH
install:
  - ./manage.sh npm_packages
  - ./manage.sh update_dev_packages
  - pip install codecov
script:
  - ./manage.sh styles
  - ./manage.sh grunt_build
  - ./manage.sh tests
after_success:
  - ./manage.sh py_test_coverage
  - codecov
notifications:
  irc:
    channels:
      - "irc.freenode.org#searx"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
    on_success: change
