language: python
sudo: false
cache:
  - directories:
    - $HOME/.cache/pip

addons:
  firefox: "latest"

install:
  - make install
  - make gecko.driver
  - make node.env
  - local/py3/bin/pip install codecov
script:
  - make themes
  - make test
after_success:
  - make test.coverage
  - codecov

stages:
  - test
  - name: docker
    if: branch = master AND type != pull_request AND env(DOCKER_USERNAME) IS present

jobs:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - stage: docker
      python: "3.6"
      git:
        depth: false
      services:
        - docker
      addons: []
      before_install: true
      install: true
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - local/py3/bin/activate; ./manage.sh docker_build push
      after_success: true

notifications:
  irc:
    channels:
      - "irc.freenode.org#searx"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
    on_success: change
