sudo: false
cache:
  - pip
  - npm
  - directories:
    - $HOME/.cache/pip
language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g less grunt-cli
  - ( cd searx/static/themes/oscar;npm install; cd - )
install:
  - ./manage.sh update_packages
  - ./manage.sh update_dev_packages
  - pip install coveralls
script:
  - ./manage.sh pep8_check
  - ./manage.sh styles
  - ./manage.sh grunt
  - ./manage.sh py_test_coverage
  - ./manage.sh robot_tests
after_success:
  coveralls
notifications:
  irc:
    channels:
      - "irc.freenode.org#searx"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
    on_success: change
