sudo: false
cache:
  - pip
  - npm
  - directories:
    - $HOME/.cache/pip
language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install less grunt-cli
  - ( cd searx/static/themes/oscar;npm install; cd - )
  - mkdir -p ~/drivers; export PATH=~/drivers:$PATH;
  - GECKODRIVER_URL="https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz";
  - FILE=`mktemp`; wget "$GECKODRIVER_URL" -qO $FILE && tar xz -C ~/drivers -f $FILE geckodriver; rm $FILE; chmod 777 ~/drivers/geckodriver;
install:
  - ./manage.sh update_dev_packages
  - pip install coveralls
script:
  - ./manage.sh styles
  - ./manage.sh grunt_build
  - ./manage.sh tests
  - ./manage.sh py_test_coverage
after_success:
  coveralls
notifications:
  irc:
    channels:
      - "irc.freenode.org#searx"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
    on_success: change
