sudo: false
cache:
  - pip
  - npm
language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g less grunt-cli
  - ( cd searx/static/themes/oscar;npm install )
install:
  - "make"
  - pip install coveralls
script:
  - "make flake8"
  - "make robot"
  - "make styles"
  - "make grunt"
  - make coverage
after_success:
  coveralls
notifications:
  irc:
    channels:
      - "irc.freenode.org#searx"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
    on_success: change
