general:
    debug : False
    instance_name : "searx_test"

search:
    safe_search : 0
    autocomplete : ""

server:
    port : 11111
    bind_address : 127.0.0.1
    secret_key : "ultrasecretkey" # change this!
    base_url : False
    image_proxy : False

ui:
    themes_path : ""
    default_theme : legacy
    default_locale : ""

outgoing:
    request_timeout : 1.0 # seconds
    useragent_suffix : ""

engines:
  - name : general_dummy
    engine : dummy
    categories : general
    shortcut : gd

  - name : dummy_dummy
    engine : dummy
    categories : dummy
    shortcut : dd

locales:
    en : English
    hu : Magyar
