server:
    port : 11111
    bind_address : 127.0.0.1
    secret_key : "ultrasecretkey" # change this!
    debug : False
    request_timeout : 3.0 # seconds
    base_url: False
    themes_path : ""
    default_theme : default
    https_rewrite : True
    image_proxy : False

engines:
  - name : general_dummy
    engine : dummy
    categories : general

  - name : dummy_dummy
    engine : dummy
    categories : dummy

locales:
    en : English
    hu : Magyar
